import type { Metadata } from "next";
import { JacquesSans, JacquesMono } from "@/font";
import "./globals.css";
import Navbar from "./component/Navbar/Navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${JacquesSans.variable} ${JacquesMono.variable} h-full antialiased`}
    >
      <body>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
